name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - run: dotnet build /home/runner/work/VoiceScript/VoiceScript/VoiceScript/DiagramModel/DiagramModel
    - run: dotnet test /home/runner/work/VoiceScript/VoiceScript/VoiceScript/DiagramModel/DiagramModel
