name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
      working-directory: VoiceScript
    - name: Build
      run: dotnet build
      working-directory: VoiceScript
    - name: Test with the dotnet CLI
      run: dotnet test
